### ISSUE TITLE
Syntax highlighting missing in hover with *.module.scss file

### ISSUE THREAD

**Issue by karlhorky** [Viijay-Kr/react-ts-css#19] opened 2023-01-06 11:59 UTC
Hi there, first of all, thanks for this extension, really great! 🙌

In the readme, it shows syntax highlighting in the hover of a class imported from a `*.module.scss` file.

However, the syntax highlighting does not appear for me:

<img width="991" alt="Screenshot 2023-01-06 at 12 48 03" src="https://user-images.githubusercontent.com/1935696/211006745-6f6251f6-95f0-4be4-9387-29dca501d991.png">

I also tried it with the square brackets syntax, but this also did not help:

<img width="1014" alt="Screenshot 2023-01-06 at 12 51 15" src="https://user-images.githubusercontent.com/1935696/211007360-cb6f6882-c692-4bb7-92dc-33a1ecb71251.png">

Also simplifying the CSS did not help:

<img width="985" alt="Screenshot 2023-01-06 at 12 55 35" src="https://user-images.githubusercontent.com/1935696/211007930-6bd6a47a-f1a2-4b60-a0d3-c801804a62a8.png">

The syntax highlighting does however work here with the [**React Style Helper** extension](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper) ([repo](https://github.com/apptools-lab/AppWorks/tree/master/extensions/style-helper)):

<img width="994" alt="Screenshot 2023-01-06 at 12 55 17" src="https://user-images.githubusercontent.com/1935696/211008694-0815c5ee-3e58-4e21-9591-54167cca121f.png">

### Code

```scss
// page.module.scss
.bodyBold {
  display: flex;

  & h2 {
    // abc
    padding: 0 40px;
  }
}
```

```ts
// page.tsx
import styles from './page.module.scss';

export default function Login() {
  return (
    <div className={styles.bodyBold}>
```

**Comment by Viijay-Kr** [comment] 2023-01-06 12:36
@karlhorky Thanks for reporting the issue . 
I will try to investigate this issue .

**Comment by Viijay-Kr** [comment] 2023-01-07 17:13
@karlhorky I could not reproduce this issue.

Can you give me more information about the version of VS code you are using plus the details of your OS

**Comment by karlhorky** [comment] 2023-01-07 17:45
Maybe it's highlighting on your system because of another extension that you have installed?

My versions:

- macOS Ventura 13.1 (22C65)
- Tested on 2 VS Code versions
  - No extensions + VS Code Insiders 1.75.0-insider
  - With some extensions + VS Code 1.74.2

**Comment by Viijay-Kr** [comment] 2023-01-07 18:08
@karlhorky I suspected it and then disabled other extensions but still couldn't reproduce it. Then again I debugged #33 in development mode without any extensions , then I was able to reproduce it.

#33 This should close this issue.

**Closed** 2023-01-07 18:21 UTC
Labels: bug

**Comment by karlhorky** [comment] 2023-01-08 09:45
@Viijay-Kr thanks for that, version `1.3.1` seems to work! 🙌

<img width="1084" alt="Screenshot 2023-01-08 at 10 43 29" src="https://user-images.githubusercontent.com/1935696/211189561-e9539012-e3c3-47c5-ab37-65640d2cc00a.png">

**Comment by karlhorky** [comment] 2023-01-08 09:49
Actually now this has been fixed, the only last feature that is missing vs [the **React Style Helper** extension](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper) is auto-import of `styles` default import from `*.module.css/scss/sass` files.

So if the feature from the issue below was implemented, then I can tell all of our students to uninstall React Style Helper and switch fully to your extension!

- https://github.com/Viijay-Kr/react-ts-css/issues/20

**Comment by Viijay-Kr** [comment] 2023-01-08 10:24
@karlhorky I can work on it.
